# Generated by Django 5.1.15 on 2026-04-22 17:14

import apps.common.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP')], max_length=8)),
                ('src_ip', models.GenericIPAddressField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('src_port', models.PositiveIntegerField(blank=True, null=True)),
                ('dst_port', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes_tx', models.BigIntegerField(default=0)),
                ('bytes_rx', models.BigIntegerField(default=0)),
                ('application', models.CharField(blank=True, default='', max_length=64)),
                ('reported_at', models.DateTimeField(db_index=True)),
                ('blocked', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='devices.virtualdevice')),
            ],
            options={
                'ordering': ('-reported_at',),
            },
        ),
    ]
