# Generated by Django 5.1.15 on 2026-04-22 17:14

import apps.common.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareBlob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('size_bytes', models.BigIntegerField()),
                ('model_codes', models.JSONField(default=list)),
                ('version', models.CharField(blank=True, default='', max_length=64)),
                ('storage_key', models.CharField(help_text='Filesystem path or S3 key', max_length=512)),
                ('state', models.CharField(choices=[('uploaded', 'Uploaded'), ('ingesting', 'Ingesting'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=32)),
                ('ingest_error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
