# Generated by Django 5.1.15 on 2026-04-22 17:14

import apps.common.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blueprints', '0001_initial'),
        ('controllers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(choices=[('creating', 'Creating'), ('ramping', 'Ramping'), ('active', 'Active'), ('paused', 'Paused'), ('tearing_down', 'Tearing down'), ('deleted', 'Deleted')], default='creating', max_length=32)),
                ('device_count', models.PositiveIntegerField(default=0)),
                ('ramp_spec', models.JSONField(blank=True, default=dict)),
                ('blueprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleets', to='blueprints.blueprint')),
                ('controller_target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleets', to='controllers.controllertarget')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
