# Generated by Django 5.1.15 on 2026-04-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='auto_adopt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fleet',
            name='model_code',
            field=models.CharField(default='USW24P250', help_text='Model every device in this fleet gets. Phase 2 blueprint support will add per-device mixing.', max_length=32),
        ),
        migrations.AddField(
            model_name='fleet',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
