# Generated by Django 5.1.15 on 2026-04-22 17:14

import apps.common.fields
import apps.common.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controllers', '0001_initial'),
        ('fleets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('mac_address', models.CharField(db_index=True, max_length=17, unique=True)),
                ('serial_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('model_code', models.CharField(max_length=32)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=32)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('key_exchange', 'Key exchange'), ('heartbeat', 'Heartbeat'), ('config_apply', 'Config apply'), ('adopted', 'Adopted'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='pending', max_length=32)),
                ('inform_key', apps.common.fields.EncryptedTextField(blank=True, default='')),
                ('inform_key_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_config_applied_at', models.DateTimeField(blank=True, null=True)),
                ('controller_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='controllers.controllertarget')),
                ('fleet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='fleets.fleet')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InformExchange',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('exchange_type', models.CharField(choices=[('adopt', 'Adopt'), ('heartbeat', 'Heartbeat'), ('config_push', 'Config push'), ('stats', 'Stats'), ('error', 'Error')], max_length=32)),
                ('payload_in', models.JSONField(blank=True, null=True)),
                ('payload_out', models.JSONField(blank=True, null=True)),
                ('exchanged_at', models.DateTimeField(db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inform_exchanges', to='devices.virtualdevice')),
            ],
            options={
                'ordering': ('-exchanged_at',),
            },
        ),
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('applied_config', models.JSONField()),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('applied_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='devices.virtualdevice')),
            ],
            options={
                'ordering': ('-applied_at',),
            },
        ),
        migrations.AddIndex(
            model_name='virtualdevice',
            index=models.Index(fields=['state'], name='devices_vir_state_16a2dc_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualdevice',
            index=models.Index(fields=['controller_target', 'state'], name='devices_vir_control_48d742_idx'),
        ),
        migrations.AddIndex(
            model_name='informexchange',
            index=models.Index(fields=['device', '-exchanged_at'], name='devices_inf_device__dd62bd_idx'),
        ),
    ]
