# Generated by Django 5.1.15 on 2026-04-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualdevice',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
