# Generated by Django 5.1.15 on 2026-04-22 17:14

import apps.common.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('model_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('model_display', models.CharField(max_length=200)),
                ('device_family', models.CharField(choices=[('ap', 'Access point'), ('switch', 'Switch'), ('gateway', 'Gateway'), ('other', 'Other')], max_length=16)),
                ('hardware_capabilities', models.JSONField(default=dict)),
                ('default_config', models.JSONField(default=dict)),
                ('schema_version', models.CharField(default='uvl-template/v1', max_length=32)),
            ],
            options={
                'ordering': ('model_code',),
            },
        ),
    ]
