# Generated by Django 5.1.15 on 2026-04-22 17:14

import apps.common.fields
import apps.common.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerTarget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('uos-server', 'UniFi OS Server'), ('legacy-network', 'Legacy Network')], default='uos-server', max_length=32)),
                ('inform_url', apps.common.fields.EncryptedTextField()),
                ('api_url', apps.common.fields.EncryptedTextField()),
                ('api_username', apps.common.fields.EncryptedTextField()),
                ('api_password', apps.common.fields.EncryptedTextField()),
                ('verify_tls', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('health', models.CharField(choices=[('ok', 'OK'), ('auth-failed', 'Auth failed'), ('unreachable', 'Unreachable'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
