# Generated by Django 5.2.17 on 2026-08-19 11:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "model",
                    models.CharField(
                        help_text="Catalogue key, e.g. usw-pro-24-poe", max_length=64
                    ),
                ),
                ("mac", models.CharField(blank=True, max_length=17)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("x", models.FloatField(default=0)),
                ("y", models.FloatField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                ("stp_enabled", models.BooleanField(default=True)),
                ("stp_priority", models.PositiveIntegerField(default=32768)),
                ("note", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "vlan_id",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4094),
                        ],
                    ),
                ),
                ("subnet", models.CharField(default="192.168.1.0/24", max_length=64)),
                ("purpose", models.CharField(default="corporate", max_length=32)),
                ("isolated", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["vlan_id"],
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "stp_mode",
                    models.CharField(
                        choices=[
                            ("rstp", "RSTP"),
                            ("stp", "STP (802.1D)"),
                            ("disabled", "Disabled"),
                        ],
                        default="rstp",
                        max_length=16,
                    ),
                ),
                ("wan_download_mbps", models.PositiveIntegerField(default=1000)),
                ("wan_upload_mbps", models.PositiveIntegerField(default=1000)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("index", models.PositiveIntegerField()),
                ("name", models.CharField(blank=True, max_length=80)),
                ("enabled", models.BooleanField(default=True)),
                ("poe_enabled", models.BooleanField(default=True)),
                ("bpdu_guard", models.BooleanField(default=False)),
                ("speed_override", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ports",
                        to="netsim.device",
                    ),
                ),
                (
                    "native_network",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ports",
                        to="netsim.network",
                    ),
                ),
            ],
            options={
                "ordering": ["device_id", "index"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[("wired", "Wired"), ("wireless", "Wireless")],
                        default="wired",
                        max_length=16,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("workstation", "Workstation"),
                            ("laptop", "Laptop"),
                            ("phone", "Phone"),
                            ("tablet", "Tablet"),
                            ("tv", "TV / media"),
                            ("server", "Server / NAS"),
                            ("camera", "Camera"),
                            ("printer", "Printer"),
                            ("iot", "IoT"),
                            ("voip", "VoIP phone"),
                        ],
                        default="workstation",
                        max_length=24,
                    ),
                ),
                ("mac", models.CharField(blank=True, max_length=17)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("down_mbps", models.FloatField(default=5)),
                ("up_mbps", models.FloatField(default=1)),
                ("rssi_dbm", models.IntegerField(default=-55)),
                (
                    "access_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wireless_clients",
                        to="netsim.device",
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients",
                        to="netsim.network",
                    ),
                ),
                (
                    "port",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients",
                        to="netsim.port",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="netsim.site",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="network",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="networks",
                to="netsim.site",
            ),
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cable",
                    models.CharField(
                        choices=[
                            ("cat5e", "Cat5e"),
                            ("cat6", "Cat6"),
                            ("cat6a", "Cat6a"),
                            ("dac", "DAC"),
                            ("fibre", "Fibre"),
                        ],
                        default="cat6",
                        max_length=16,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "a_port",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_a",
                        to="netsim.port",
                    ),
                ),
                (
                    "b_port",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_b",
                        to="netsim.port",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="netsim.site",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Flow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("enabled", models.BooleanField(default=True)),
                ("protocol", models.CharField(default="tcp", max_length=8)),
                ("mbps", models.FloatField(default=100)),
                ("burstiness", models.FloatField(default=0.15)),
                (
                    "src_kind",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("device", "Device"),
                            ("internet", "Internet"),
                        ],
                        default="client",
                        max_length=16,
                    ),
                ),
                (
                    "dst_kind",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("device", "Device"),
                            ("internet", "Internet"),
                        ],
                        default="internet",
                        max_length=16,
                    ),
                ),
                (
                    "dst_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flows_in",
                        to="netsim.client",
                    ),
                ),
                (
                    "dst_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flows_in",
                        to="netsim.device",
                    ),
                ),
                (
                    "src_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flows_out",
                        to="netsim.client",
                    ),
                ),
                (
                    "src_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flows_out",
                        to="netsim.device",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flows",
                        to="netsim.site",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="device",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="netsim.site",
            ),
        ),
        migrations.AddConstraint(
            model_name="port",
            constraint=models.UniqueConstraint(
                fields=("device", "index"), name="unique_port_index_per_device"
            ),
        ),
        migrations.AddConstraint(
            model_name="network",
            constraint=models.UniqueConstraint(
                fields=("site", "vlan_id"), name="unique_vlan_per_site"
            ),
        ),
    ]
